
export const CLICK = "CLICK_MOUSE";
export const INCREMENT = "INCREMENT";
export const LOCATION_CHANGE = "router.LOCATION_CHANGE";
export const CHANGE_TRANSPARENT_MENU = "CHANGE_TRANSPARENT_MENU";
export const TO_CHANGE_TRANSPARENT_MENU = "TO_CHANGE_TRANSPARENT_MENU";
