
export const CLICK = "CLICK_MOUSE";
export const INCREMENT = "INCREMENT";
export const LOCATION_CHANGE = "router.LOCATION_CHANGE";
export const CHANGE_TRANSPARENT_MENU = "CHANGE_TRANSPARENT_MENU";
export const TO_CHANGE_TRANSPARENT_MENU = "TO_CHANGE_TRANSPARENT_MENU";
export const CHANGE_HOME_MAP_POINT = "CHANGE_HOME_MAP_POINT";
export const TOOGLE_EARLY_ACCESS_MODAL = "TOOGLE_EARLY_ACCESS_MODAL";
